# fly.toml app configuration file generated for inventory-application-alyoshka on 2023-08-31T19:48:10-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "inventory-application-alyoshka"
primary_region = "ord"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
